version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "80:80"    # Exposes HTTP on port 80
      - "443:443"  # Exposes HTTPS on port 443
    environment:
      - SOME_ENV_VARIABLE=value
    volumes:
      - ./app:/usr/src/app  # Syncs local app folder to the container
    networks:
      - app-network
    restart: unless-stopped  # Automatically restarts the container if it crashes

networks:
  app-network:
    driver: bridge
